/*
 * This file is generated by jOOQ.
 */
package com.ykbt.jooq;


import com.ykbt.jooq.tables.User;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in ormdb
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>ormdb.user</code>.
     */
    public static final User USER = com.ykbt.jooq.tables.User.USER;
}
